#!/usr/bin/env bash

usage() {
  cat <<EOF
Lists unbound Persistent Volume Claims in a Kubernetes cluster.
Usage:
  unbound-pvc [-l|--list|-n|--namespace|-h]
Examples:
  # List unbound PVCs in a specific namespace
  kubectl unbound-pvc -n test
  # List all PVCs in all namespaces
  kubectl unbound-pvc -l
Flags:
  -l, --list          List all unbound PVCs in all namespaces
  -n, --namespace     List unbound PVC in a specific namespace
  -h, --help          Show this help message
EOF
}

jq_missing() {
  cat <<EOF
You must install jq to use this plugin:
    https://github.com/stedolan/jq
INSTALLATION
Homebrew (macOS):
    brew install jq
For Linux platforms and Windows, see:
    https://stedolan.github.io/jq/download/
EOF
}

unbound_pvc() {
    if [[ $1 == "--all-namespaces" ]]; then
        cmd1=$(kubectl get pvc -o json --all-namespaces | jq -r '.items[].status.phase')
	    if [[ `echo ${cmd1} | wc -w` -ge 1 ]]
	    then
	        kubectl get pvc --all-namespaces -o=custom-columns='NAME:.metadata.name,STATUS:.status.phase' | awk '$2!="Bound"'
	    fi

    else
        cmd1=$(kubectl get pvc -o json -n "${namespace}" | jq -r '.items[].status.phase')
        if [[ `echo ${cmd1} | wc -w` -ge 1 ]]
	    then
	        kubectl get pvc -n "${namespace}" -o=custom-columns='NAME:.metadata.name,STATUS:.status.phase' | awk '$2!="Bound"'
	    fi
    fi
}

check_args_and_deps() {
    if ! [[ -x "$(command -v jq)" ]]; then
        jq_missing
        exit 1
    fi
    while : ; do
        case "$1" in
        -h|--help)
            usage
	    exit
            ;;
        -l|--list)
            unbound_pvc "--all-namespaces"
	    exit
            ;;
        -n|--namespace)
            namespace=$2
            unbound_pvc "${namespace}"
	    exit
            ;;
        *)
            usage
	    exit
            ;;
        esac
    done
}

check_args_and_deps "$@"
